version: '3'
services:

  barathrum:
    image: tempestmon/barathrum:v0.0.1
    container_name: barathrum
    restart: unless-stopped
    command: run.py
    env_file:
      - common.env
      - backend.env
    environment:
      FLASK_DEBUG: true
    ports:
      - "5000:5000"
    networks:
      - backend

  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    env_file:
      - common.env
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
